services:
  - type: web
    name: patitas-server
    env: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        value: https://patitas-client.vercel.app
        sync: false
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        value: 5432
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_DATABASE
        value: patitas_db
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_ENCRYPTION_KEY
        sync: false

databases:
  - name: patitas-postgres
    region: ohio
    plan: free
    databaseName: patitas_db
    ipAllowList: []
